secrets:
  s3host: { file: ./.secret/.s3host }
  s3port: { file: ./.secret/.s3port }
  s3region: { file: ./.secret/.s3region }
  s3bucket: { file: ./.secret/.s3bucket }
  s3access: { file: ./.secret/.s3access }
  s3secret: { file: ./.secret/.s3secret }
networks:
  bridge: { external: true, name: net }
services:
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-base:
    profiles: [_]
    container_name: pyroscope-base
    image: grafana/pyroscope:latest
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: configMap
    networks: [bridge]
    ports: ["3400","3401"]
    secrets:
      - { source: s3host, target: /run/secrets/s3host/s3host }
      - { source: s3port, target: /run/secrets/s3port/s3port }
      - { source: s3region, target: /run/secrets/s3region/s3region }
      - { source: s3bucket, target: /run/secrets/s3bucket/s3bucket }
      - { source: s3access, target: /run/secrets/s3access/s3access }
      - { source: s3secret, target: /run/secrets/s3secret/s3secret }
    entrypoint: [sh]
    user: ${UID}:${GID}
    volumes:
      - ./docker-entry.sh:/entrypoint:ro
      - ./etc.config.yml:/etc/config/pyroscope.yml:ro
      - ./../.volume/data:/data
      - ./../.volume/tmp:/tmp
      - ./../.volume/log:/var/log
    environment:
      - TZ=Asia/Jakarta
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-all:
    profiles: [all]
    container_name: pyroscope-all
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, all]
    depends_on: []
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-distributor:
    profiles: [cluster]
    container_name: pyroscope-distributor
    extends: { service: pyroscope-base }
    ports: ["3400:3400"]
    entrypoint: [/entrypoint, distributor]
    depends_on: [pyroscope-ingester-0, pyroscope-ingester-1, pyroscope-ingester-2]
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-ingester-0:
    profiles: [cluster]
    container_name: pyroscope-ingester-0
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, ingester, "-0"]
    depends_on: []
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-ingester-1:
    profiles: [cluster]
    container_name: pyroscope-ingester-1
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, ingester, "-1"]
    depends_on: []
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-ingester-2:
    profiles: [cluster]
    container_name: pyroscope-ingester-2
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, ingester, "-2"]
    depends_on: []
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-query-scheduler:
    profiles: [cluster]
    container_name: pyroscope-query-scheduler
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, query-scheduler]
    depends_on: []
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-query-frontend:
    profiles: [cluster]
    container_name: pyroscope-query-frontend
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, query-frontend]
    depends_on: []
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-querier-0:
    profiles: [cluster]
    container_name: pyroscope-querier-0
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, querier, "-0"]
    depends_on: [pyroscope-query-frontend]
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-querier-1:
    profiles: [cluster]
    container_name: pyroscope-querier-1
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, querier, "-1"]
    depends_on: [pyroscope-query-frontend]
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-querier-2:
    profiles: [cluster]
    container_name: pyroscope-querier-2
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, querier, "-2"]
    depends_on: [pyroscope-query-frontend]
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-compactor:
    profiles: [cluster]
    container_name: pyroscope-compactor
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, compactor]
    depends_on: [pyroscope-ingester-0]
  # --------------------------------------------------------------------------------------------------------------------
  pyroscope-store-gateway:
    profiles: [cluster]
    container_name: pyroscope-store-gateway
    extends: { service: pyroscope-base }
    entrypoint: [/entrypoint, store-gateway]
    depends_on: [pyroscope-ingester-0]
  # --------------------------------------------------------------------------------------------------------------------
