version: "3"
networks:
  bridge: { external: true, name: net }
secrets:
  pgdb: { file: ./.secret/.pg-database }
  pgpw: { file: ./.secret/.pg-password }
  pgun: { file: ./.secret/.pg-username }
  pgpwro: { file: ./.secret/.pgreadonly-password }
  pgunro: { file: ./.secret/.pgreadonly-username }
  pgpwrp: { file: ./.secret/.pgreplication-password }
  pgunrp: { file: ./.secret/.pgreplication-username }
  pgslrp: { file: ./.secret/.pgreplication-slot }
services:
  # --------------------------------------------------------------------------------------------------------------------
  postgres-primary:
    container_name: postgres-primary
    image: postgres:alpine
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: configMap
    restart: "no"
    networks: [bridge]
    ports: [5432:5432]
    entrypoint: [/entrypoint]
    volumes:
      - ./docker-entry.primary.sh:/entrypoint:ro
      - ./docker-health.primary.sh:/healthcheck:ro
      - ./docker-init.primary.sh:/docker-entrypoint-initdb.d/init.sh:ro
      - ./etc.postgres.conf:/etc/config/postgres.conf:ro
      - ./../.volume/data:/data
      - ./../.volume/log:/var/log
    secrets:
      - { source: pgdb, target: /run/secrets/pgdb/pgdb }
      - { source: pgun, target: /run/secrets/pgun/pgun }
      - { source: pgpw, target: /run/secrets/pgpw/pgpw }
      - { source: pgunro, target: /run/secrets/pgunro/pgunro }
      - { source: pgpwro, target: /run/secrets/pgpwro/pgpwro }
      - { source: pgunrp, target: /run/secrets/pgunrp/pgunrp }
      - { source: pgpwrp, target: /run/secrets/pgpwrp/pgpwrp }
      - { source: pgslrp, target: /run/secrets/pgslrp/pgslrp }
    environment:
      - TZ=Asia/Jakarta
      - LANG=en_US.utf8
      - PGDATA=/data/postgres-primary
      - POSTGRES_DB_FILE=/run/secrets/pgdb/pgdb
      - POSTGRES_USER_FILE=/run/secrets/pgun/pgun
      - POSTGRES_PASSWORD_FILE=/run/secrets/pgpw/pgpw
    healthcheck: 
      test: [CMD-SHELL, /healthcheck]
      interval: 3s
      timeout: 3s
      retries: 9
  # --------------------------------------------------------------------------------------------------------------------
  postgres-standby:
    container_name: postgres-standby
    image: postgres:alpine
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: configMap
    restart: "no"
    networks: [bridge]
    ports: [5433:5432]
    entrypoint: [/entrypoint]
    volumes:
      - ./docker-entry.standby.sh:/entrypoint:ro
      - ./../.volume/data:/data
      - ./../.volume/log:/var/log
    secrets:
      - { source: pgunrp, target: /run/secrets/pgunrp/pgunrp }
      - { source: pgpwrp, target: /run/secrets/pgpwrp/pgpwrp }
      - { source: pgslrp, target: /run/secrets/pgslrp/pgslrp }
    environment:
      - TZ=Asia/Jakarta
      - LANG=en_US.utf8
      - PGDATA=/data/postgres-standby
    depends_on:
      postgres-primary: { condition: service_healthy }
  # --------------------------------------------------------------------------------------------------------------------
