networks:
  bridge: { external: true, name: net }
services:
  # --------------------------------------------------------------------------------------------------------------------
  grafana:
    container_name: grafana
    image:  grafana/grafana-enterprise:latest 
    labels:
      kompose.service.type: nodeport
      kompose.volume.type: configMap
    networks: [bridge]
    ports: [3000:3000]
    user: ${UID}:${GID}
    volumes:
      - ./provisioning/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml:ro
      - ./etc.grafana.ini:/etc/grafana/grafana.ini:ro
      - ./../.volume/tmp:/tmp
      - ./../.volume/log:/var/log
    environment:
      - TZ=Asia/Jakarta
  