# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#server
multitenancy_enabled: false
# no_auth_tenant: anonymous
max_separate_metrics_groups_per_user: 1_000
enable_go_runtime_metrics: true
# ----------------------------------------------------------------------------------------------------------------------
api:
  skip_label_name_validation_header_enabled: false
  alertmanager_http_prefix: /alertmanager
  prometheus_http_prefix: "/prometheus" # /prometheus
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#server
# 
server:
  # grpc_listen_address: ""
  grpc_listen_port: 3301 # default=9095
  # http_listen_address: ""
  http_listen_port: 3300 # default=8080
  log_level: warn
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#distributor
# 
distributor:
  # pool:
  #   client_cleanup_period: 15s
  #   health_check_ingesters: true
  ring:
    kvstore:
      store: memberlist
    # instance_addr: 127.0.0.1
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#querier
# 
querier:
  query_store_after: 12h
  max_query_into_future: 10m
  # store_gateway_client: null
  shuffle_sharding_ingesters_enabled: true
  prefer_streaming_chunks: false
  streaming_chunks_per_ingester_series_buffer_size: 512
  max_concurrent: 20
  timeout: 2m
  max_samples: 50_000_000
  default_evaluation_interval: 1m
  lookback_delta: 5m
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ingester_client
# 
# ingester_client: null
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ingester
# 
ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1
    # instance_addr: 127.0.0.1
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#flusher
# 
flusher:
  exit_after_flush: true
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#limits
# 
# limits:
#   request_rate: 0
#   request_burst_size: 0
#   ingestion_rate: 10000
#   ingestion_burst_size: 200000
#   accept_ha_samples: false
#   ha_cluster_label: "cluster"
#   ha_replica_label: "__replica__"
#   ha_max_clusters: 100
#   drop_labels: []
#   max_label_name_length: 1024
#   max_label_value_length: 2048
#   max_label_names_per_series: 30
#   max_metadata_length: 1024
#   max_native_histogram_buckets: 0
#   creation_grace_period: 10m
#   enforce_metadata_metric_name: true
#   ingestion_tenant_shard_size: 0
#   metric_relabel_configs: null
#   max_global_series_per_user: 150000
#   max_global_series_per_metric: 0
#   max_global_metadata_per_user: 0
#   max_global_metadata_per_metric: 0
#   max_global_exemplars_per_user: 0
#   native_histograms_ingestion_enabled: false
#   active_series_custom_trackers: null
#   out_of_order_time_window: 0s
#   out_of_order_blocks_external_label_enabled: false
#   separate_metrics_group_label: ""
#   max_fetched_chunks_per_query: 2000000
#   max_fetched_series_per_query: 0
#   max_fetched_chunk_bytes_per_query: 0
#   max_query_lookback: 0s
#   max_partial_query_length: 0s
#   max_query_parallelism: 14
#   max_labels_query_length: 0s
#   max_cache_freshness: 1m
#   max_queriers_per_tenant: 0
#   query_sharding_total_shards: 16
#   query_sharding_max_sharded_queries: 128
#   query_sharding_max_regexp_size_bytes: 4096
#   split_instant_queries_by_interval: 0s
#   query_ingesters_within: 13h
#   max_total_query_length: 0s
#   results_cache_ttl: 1w
#   results_cache_ttl_for_out_of_order_time_window: 10m
#   max_query_expression_size_bytes: 0
#   cardinality_analysis_enabled: false
#   label_names_and_values_results_max_size_bytes: 419430400
#   label_values_max_cardinality_label_names_per_request: 100
#   ruler_evaluation_delay_duration: 1m
#   ruler_tenant_shard_size: 0
#   ruler_max_rules_per_rule_group: 20
#   ruler_max_rule_groups_per_tenant: 70
#   ruler_recording_rules_evaluation_enabled: true
#   ruler_alerting_rules_evaluation_enabled: true
#   ruler_sync_rules_on_changes_enabled: true
#   store_gateway_tenant_shard_size: 0
#   compactor_blocks_retention_period: 0s
#   compactor_split_and_merge_shards: 0
#   compactor_split_groups: 1
#   compactor_tenant_shard_size: 0
#   compactor_partial_block_deletion_delay: 1d
#   compactor_block_upload_enabled: false
#   compactor_block_upload_validation_enabled: true
#   compactor_block_upload_verify_chunks: true
#   compactor_block_upload_max_block_size_bytes: 0
#   s3_sse_type: ""
#   s3_sse_kms_key_id: ""
#   s3_sse_kms_encryption_context: ""
#   alertmanager_receivers_firewall_block_cidr_networks: ""
#   alertmanager_receivers_firewall_block_private_addresses: false
#   alertmanager_notification_rate_limit: 0
#   alertmanager_notification_rate_limit_per_integration: {}
#   alertmanager_max_config_size_bytes: 0
#   alertmanager_max_templates_count: 0
#   alertmanager_max_template_size_bytes: 0
#   alertmanager_max_dispatcher_aggregation_groups: 0
#   alertmanager_max_alerts_count: 0
#   alertmanager_max_alerts_size_bytes: 0
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend_worker
# 
frontend_worker:
  frontend_address: mimir-query-frontend:3301
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend
# 
# frontend:
#   log_queries_longer_than: 0s
#   log_query_request_headers: ""
#   max_body_size: 10485760
#   query_stats_enabled: true
#   max_outstanding_per_tenant: 100
#   querier_forget_delay: 0s
#   scheduler_address: ""
#   scheduler_dns_lookup_period: 10s
#   scheduler_worker_concurrency: 5
#   # grpc_client_config: null
#   # instance_interface_names: null
#   address: ""
#   port: 0
#   split_queries_by_interval: 24h
#   align_queries_with_step: false
#   results_cache:
#     backend: "" # options: memcached, redis
#     memcached: null
#     redis: null
#     compression: ""
#   cache_results: false
#   max_retries: 5
#   parallelize_shardable_queries: false
#   cache_unaligned_requests: false
#   query_sharding_target_series_per_shard: 0
#   query_result_response_format: "protobuf"
#   downstream_url: ""
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#blocks_storage
# 
blocks_storage:
  backend: s3
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#compactor
# 
# compactor:
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#store_gateway
store_gateway:
  sharding_ring:
    replication_factor: 1
# ----------------------------------------------------------------------------------------------------------------------
tenant_federation:
  enabled: false
# ----------------------------------------------------------------------------------------------------------------------
activity_tracker:
  # filepath: /tmp/mimir/metrics-activity.log
  max_entries: 1024
# vault:
#   enabled: false
#   url: ""
#   token: ""
#   mount_path: ""
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ruler
# 
# ruler:
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ruler_storage
# 
ruler_storage:
  backend: local # options: s3, gcs, azure, swift, filesystem, local
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#alertmanager
# 
# alertmanager:
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#alertmanager_storage
# 
alertmanager_storage:
  backend: local # options: s3, gcs, azure, swift, filesystem, local
# ----------------------------------------------------------------------------------------------------------------------
# runtime_config:
#   period: 10s
#   file: ""
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#memberlist
# 
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  join_members:
  - mimir-ingester-0:7946
  - mimir-ingester-1:7946
  - mimir-ingester-2:7946
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#query_scheduler
# 
# query_scheduler: {}
# ----------------------------------------------------------------------------------------------------------------------
usage_stats:
  enabled: true
  installation_mode: custom
# ----------------------------------------------------------------------------------------------------------------------
# overrides_exporter:
#   ring:
#     enabled: false
#     kvstore:
#       store: memberlist
#       prefix: collectors/
#       consul: {}
#       etcd: {}
#       multi:
#         primary: ""
#         secondary: ""
#         mirror_enabled: false
#         mirror_timeout: 2s
#     heartbeat_period: 15s
#     heartbeat_timeout: 1m
#     instance_id: ""
#     instance_interface_names: []
#     instance_port: 0
#     instance_addr: ""
#     instance_enable_ipv6: false
#     wait_stability_min_duration: 0s
#     wait_stability_max_duration: 5m
# ----------------------------------------------------------------------------------------------------------------------
common:
  storage:
    backend: s3 # options: s3, gcs, azure, swift, filesystem
    s3:
      region: ""
      insecure: true
