# Enables authentication through the X-Scope-OrgID header, which must be present
# if true. If false, the OrgID will always be set to 'fake'.
# CLI flag: -auth.enabled
auth_enabled: false # default = "all"


# The amount of virtual memory in bytes to reserve as ballast in order to
# optimize garbage collection. Larger ballasts result in fewer garbage
# collection passes, reducing CPU overhead at the cost of heap size. The ballast
# will not consume physical memory, because it is never read from. It will,
# however, distort metrics, because it is counted as live memory.
# CLI flag: -config.ballast-bytes
ballast_bytes: 0 # default = 0

# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#server
# 
# Configures the server of the launched module(s).
server:
  # grpc_listen_address: ""
  grpc_listen_port: 3101 # default=9095
  # http_listen_address: ""
  http_listen_port: 3100 # default=3100
  log_level: warn
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#distributor
# 
# Configures the distributor.
distributor:
  ring:
    kvstore:
      store: memberlist
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#querier
# 
# Configures the querier. Only appropriate when running all modules or just the
# querier.
querier:
  max_concurrent: 20
  query_store_only: false
  query_ingester_only: false
  engine:
    timeout: 5m0s
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#query_scheduler
# 
# The query_scheduler block configures the Loki query scheduler. When configured
# it separates the tenant query queues from the query-frontend.
query_scheduler:
  scheduler_ring:
    kvstore:
      store: memberlist
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#frontend
# 
# The frontend block configures the Loki query-frontend.
frontend:
  query_stats_enabled: false
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#query_range
# 
# The query_range block configures the query splitting and caching in the Loki
# query-frontend.
query_range:
  results_cache:
    cache:
      enable_fifocache : false
      embedded_cache:
        enabled: true
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#ruler
# 
# The ruler block configures the Loki ruler.
ruler:
  ring:
    kvstore:
      store: memberlist
  # rule_path: /tmp/loki/rules
  # alertmanager_url: localhost:9093
  wal:
    dir: ruler-wal
  # remote_write:
  #   clients:
  #     mimir:
  #       url: http://mimir-distributor:3300/api/v1/push
  #       send_exemplars: true
  #       send_native_histograms: true
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#ingester_client
# 
# The ingester_client block configures how the distributor will connect to
# ingesters. Only appropriate when running all components, the distributor, or
# the querier.
# ingester_client: null
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#ingester
# 
# The ingester block configures the ingester and how the ingester will register
# itself to a key value store.
ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
  wal:
    enabled: true
  #   dir: ingester-wal
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#index_gateway
# 
# The index_gateway block configures the Loki index gateway server, responsible
# for serving index queries without the need to constantly interact with the
# object store.
index_gateway:
  ring:
    kvstore:
      store: memberlist
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#storage_config
# 
# The storage_config block configures one of many possible stores for both the
# index and chunks. Which configuration to be picked should be defined in
# schema_config block.
storage_config:
  aws:
    # # CLI flag: -s3.buckets
    # bucketnames: ""
    # # CLI flag: -s3.endpoint
    # endpoint: ""
    # # CLI flag: -s3.access-key-id
    # access_key_id: ""
    # # CLI flag: -s3.secret-access-key
    # secret_access_key: ""
    
    s3forcepathstyle: true
    signature_version: v4
    storage_class: STANDARD
    # region: ""
    # insecure: true
  boltdb_shipper:
    # active_index_directory: /tmp/loki/index
    # cache_location: /tmp/loki/index_cache
    shared_store: s3
  index_queries_cache_config:
    enable_fifocache : false
    embedded_cache:
      enabled: true
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#chunk_store_config
# 
# The chunk_store_config block configures how chunks will be cached and how long
# to wait before saving them to the backing store.
chunk_store_config:
  chunk_cache_config:
    enable_fifocache : false
    embedded_cache:
      enabled: true
  write_dedupe_cache_config:
    enable_fifocache : false
    embedded_cache:
      enabled: true
  cache_lookups_older_than: 0s
  max_look_back_period: 0s
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#schema_config
# 
# Configures the chunk index schema and where it is stored.
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper # options: aws, aws-dynamo, gcp, bigtable, bigtable-hashed, cassandra, boltdb or boltdb-shipper
      object_store: aws # options: aws, azure, gcp, bigtable, gcs, cassandra, swift, filesystem or a named_store
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        prefix: chunk_
        period: 24h
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#compactor
# 
# The compactor block configures the compactor component, which compacts index
# shards for performance.
compactor:
  shared_store: s3 # gcs, s3, azure, swift, filesystem, bos
  compactor_ring:
    kvstore:
      store: memberlist
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#limits_config
# 
# The limits_config block configures global and per-tenant limits in Loki.
limits_config:
  query_timeout: 5m0s
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#frontend_worker
# 
# The frontend_worker configures the worker - running within the Loki querier -
# picking up and executing queries enqueued by the query-frontend.
frontend_worker:
  frontend_address: loki-query-frontend:3101
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#table_manager
# 
# The table_manager block configures the table manager for retention.
# table_manager: null
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#memberlist
# 
# Configuration for memberlist client. Only applies if the selected kvstore is
# memberlist.
# 
# When a memberlist config with atleast 1 join_members is defined, kvstore of
# type memberlist is automatically selected for all the components that require
# a ring unless otherwise specified in the component's configuration section.
memberlist:
  abort_if_cluster_join_fails: false
  # advertise_port: 7946
  bind_port: 7946
  join_members:
  - loki-ingester-0:7946
  - loki-ingester-1:7946
  - loki-ingester-2:7946
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#runtime_config
# 
# Configuration for 'runtime config' module, responsible for reloading runtime
# configuration file.
# runtime_config: null
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#tracing
# 
# Configuration for tracing.
tracing:
  enabled: true
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#analytics
# 
# Configuration for usage report.
analytics:
  reporting_enabled: false
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/loki/latest/configuration/#common
# 
# Common configuration to be shared between multiple modules. If a more specific
# configuration is given in other sections, the related configuration within
# this section will be ignored.
common:
  # path_prefix: ""
  storage:
    s3:
      s3forcepathstyle: true
      signature_version: v4
      storage_class: STANDARD
  replication_factor: 3
  ring:
    kvstore:
      store: memberlist
    # instance_addr: 127.0.0.1
  compactor_address: http://loki-compactor:3100
  compactor_grpc_address: loki-compactor:3101
# ----------------------------------------------------------------------------------------------------------------------
# How long to wait between SIGTERM and shutdown. After receiving SIGTERM, Loki
# will report 503 Service Unavailable status via /ready endpoint.
# CLI flag: -shutdown-delay
# shutdown_delay: 1s
