# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#server
multitenancy_enabled: false
# no_auth_tenant: anonymous
max_separate_metrics_groups_per_user: 1_000
enable_go_runtime_metrics: true
# ----------------------------------------------------------------------------------------------------------------------
api:
  skip_label_name_validation_header_enabled: false
  alertmanager_http_prefix: /alertmanager
  prometheus_http_prefix: "/prometheus" # /prometheus
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#server
server:
  # grpc_listen_address: ""
  grpc_listen_port: 3301 # default=9095
  # http_listen_address: ""
  http_listen_port: 3300 # default=8080
  log_level: warn
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#distributor
distributor:
  # pool:
  #   client_cleanup_period: 15s
  #   health_check_ingesters: true
  ring:
    kvstore:
      store: memberlist
    # instance_addr: 127.0.0.1
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#querier
querier:
  # query_store_after: 12h
  # max_query_into_future: 10m
  # store_gateway_client: null
  # shuffle_sharding_ingesters_enabled: true
  # prefer_streaming_chunks: false
  # prefer_streaming_chunks_from_ingesters: true
  # prefer_streaming_chunks_from_store_gateways: false
  # streaming_chunks_per_ingester_series_buffer_size: 512
  max_concurrent: 20
  timeout: 2m
  # max_samples: 50_000_000
  # default_evaluation_interval: 1m
  # lookback_delta: 5m
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#query_scheduler
query_scheduler:
  ring:
    kvstore:
      store: memberlist
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend
frontend:
  query_stats_enabled: false
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#frontend_worker
frontend_worker:
  frontend_address: ""
  # frontend_address: mimir-query-frontend:3301
  # scheduler_address: mimir-query-scheduler:3301
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ruler
ruler:
  query_stats_enabled: false
  ring:
    kvstore:
      store: memberlist
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ingester
ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1
    # instance_addr: 127.0.0.1
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#flusher
flusher:
  exit_after_flush: true
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#limits
# limits:
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#blocks_storage
blocks_storage:
  backend: s3
  # storage_prefix: ""
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#compactor
compactor:
  sharding_ring:
    kvstore:
      store: "memberlist"
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#store_gateway
store_gateway:
  sharding_ring:
    kvstore:
      store: "memberlist"
# ----------------------------------------------------------------------------------------------------------------------
tenant_federation:
  enabled: false
# ----------------------------------------------------------------------------------------------------------------------
activity_tracker:
  # filepath: /tmp/mimir/metrics-activity.log
  max_entries: 1024
# vault:
#   enabled: false
#   url: ""
#   token: ""
#   mount_path: ""
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#ruler_storage
ruler_storage:
  backend: s3 # options: s3, gcs, azure, swift, filesystem, local
  storage_prefix: "ruler"
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#alertmanager
alertmanager:
  sharding_ring:
    kvstore:
      store: memberlist #: consul, etcd, inmemory, memberlist, multi
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#alertmanager_storage
alertmanager_storage:
  backend: s3 # options: s3, gcs, azure, swift, filesystem, local
  storage_prefix: "alertmanager"
# ----------------------------------------------------------------------------------------------------------------------
# runtime_config:
#   period: 10s
#   file: ""
# ----------------------------------------------------------------------------------------------------------------------
# https://grafana.com/docs/mimir/latest/references/configuration-parameters/#memberlist
memberlist:
  abort_if_cluster_join_fails: false
  bind_port: 7946
  # join_members:
  # - mimir-all:7946
  # - mimir-ingester-0:7946
  # - mimir-ingester-1:7946
  # - mimir-ingester-2:7946
# ----------------------------------------------------------------------------------------------------------------------
usage_stats:
  enabled: true
  installation_mode: custom
# ----------------------------------------------------------------------------------------------------------------------
# overrides_exporter:
#   ring:
#     enabled: false
#     kvstore:
#       store: memberlist
#       prefix: collectors/
#       consul: {}
#       etcd: {}
#       multi:
#         primary: ""
#         secondary: ""
#         mirror_enabled: false
#         mirror_timeout: 2s
#     heartbeat_period: 15s
#     heartbeat_timeout: 1m
#     instance_id: ""
#     instance_interface_names: []
#     instance_port: 0
#     instance_addr: ""
#     instance_enable_ipv6: false
#     wait_stability_min_duration: 0s
#     wait_stability_max_duration: 5m
# ----------------------------------------------------------------------------------------------------------------------
common:
  storage:
    backend: s3 # options: s3, gcs, azure, swift, filesystem
    s3:
      region: ""
      insecure: true
